- name: pass
  hosts: all

  vars_prompt:
    - name: ansible_password
      prompt: Пароль для подключения
      private: yes

##########################################################################################################################################################################################################
#НАСТРОЙКА СИНХРОНИЗАЦИИ КОНФИГУРАЦИОННЫХ ФАЙЛОВ СЕРВЕРОВ LINUX С КОНФИГУРАЦИОННЫМИ ФАЙЛАМИ GITLAB
- name: 
  hosts: serv1C

  vars:
    script_path: /ansible/distr/scripts_backup/versioning_configs.py # Путь к скрипту синхронизации конфигурационных файлов, на хосте, где запускается ansible
    script_dir_dist: /opt/1cv8/scripts/versioning_configs.py # Путь сохранения скрипта на удаленном сервере
    host_url: some_host_url # URL хоста GitLab
    private_token: '' # Токен доступа к подгруппе tst или prod

  roles:
    - versioning_linux_configs # Установка необходимых пакетов и добавление в CRON задания выполнения скрипта синхронизации конфигов GitLab каждый час
