- name: pass
  hosts: all

  vars_prompt:
    - name: ansible_password
      prompt: Пароль для подключения
      private: yes

##########################################################################################################################################################################################################
#УСТАНОВКА СЕРВЕРА 1С ПРЕДПРИЯТИЯ
- name: installing server 1С
  hosts: serv1C

  vars:
    inst_deb_dir: /ansible/distr/deb # Директория с инсталами deb пакетов на сервере, в которые есть еще один уровень каталогов - переменная deb_dir, которые относятся к определенным ролям и уже в этом каталоге расположены deb-файлы, которые должны быть установлены. Значение по умолчанию задается в .../install_deb_packages/defaults/main.yml
    deb_dir: for_platform_1C # каталог в директории inst_deb_dir в которой лежат инсталлы deb пакетов    
    temp_dir_1c: /var/1C # Директория, которая примонтирована на отдельную партицию для размещения темпа 1С. В ней будут папки серверов 1С.  
    inst_dir_scripts: /ansible/distr/scripts/ # Директория с скриптами
    ins_dir_dest: /home/ivanov_ii/distr/platform # директория на хосте куда нужно копировать файл установки платформы. 
    ins_dir_src: /ansible/distr/platform # директория откуда нужно копировать файл установки платформы.
    onec_version_name: 8.3.22.1851 # версия платформы 1С
    inst_dir_fonts: ./fonts # Директория откуда нужно копировать шрифты. Они разложены по папкам и находятся в папке truetype
    
    #####################################################################################################################################
    # Переопределение запуска службы сервера, если не нужно, то закоменить, значения по умолчанию заданы в defaults file for install_1C
    #SRV1CV8_DEBUG: '"-debug -http"' # признак необходимости запуска сервера отладки под http. Значение по умолчанию пусто (отладка отключена) в .../install_ragent/defaults/main.yml Если нужно включить, то раскоментируйте строку
    #SRV1CV8_DEBUG: -debug # признак необходимости запуска сервера отладки под tcp. по умолчанию отладка отключена. Если нужно включить, то раскоментируйте строку
    #SRV1CV8_PORT: 1540 # Порт запуска ragent, Значение по умолчанию 1540 в .../install_ragent/defaults/main.yml, если нужно переопределить, то раскоментируйте строку и замените на требуемое значение
    #SRV1CV8_REGPORT: 1541 # Порт запуска rmngr, Значение по умолчанию 1541 в .../install_ragent/defaults/main.yml, если нужно переопределить, то раскоментируйте строку и замените на требуемое значение
    #SRV1CV8_RANGE: 1560:1591 # Диапазон портов рабочих процессов, Значение по умолчанию 1560:1591 в .../install_ragent/defaults/main.yml если нужно переопределить, то раскоментируйте строку и замените на требуемое значение
    #RAS_PORT: 1545 # Порт сервера администрирования, Значение по умолчанию 1545 в .../install_ras/defaults/main.yml если не задан, то ставиться не будет
    #RAS_PORT:  # Если не нужно ставить сервер администирования, то нужно раскоменить эту строчку
    #####################################################################################################################################

  roles:
    - install_deb_packages # Установка пакета fontconfig
    - first_setup # Первоначальная установка - создание пользователя 1С, группы пользователей, каталогов программы, копирование шрифтов 
    - install_1C # копирования файла установки 1С и запуск скрипта установски сервера 1С
    - install_ragent # Установка службы сервера 1С по требуемому порту
    - install_ras # Установка службы удаленного администрирования 1С


#Пример установки дополнительного сервера на другом порту и установкой отладки по http протоколу
- name: installing addishional services of server 1С
  hosts: serv1C_add

  vars:
    onec_version_name: 8.3.21.1393 # версия платформы 1С
    flag_Remove_old_1C_service: false # Флаг, что не нужно удалять старые службы 1С. По умолчанию true
        
    #####################################################################################################################################
    # Переопределение запуска службы сервера, если не нужно, то закоменить, значения по умолчанию заданы в defaults file for install_1C
    SRV1CV8_DEBUG: '"-debug -http"' # признак необходимости запуска сервера отладки под http. Значение по умолчанию пусто (отладка отключена) в .../install_ragent/defaults/main.yml Если нужно включить, то раскоментируйте строку
    #SRV1CV8_DEBUG: -debug # признак необходимости запуска сервера отладки под tcp. по умолчанию отладка отключена. Если нужно включить, то раскоментируйте строку
    SRV1CV8_PORT: 2540 # Порт запуска ragent, Значение по умолчанию 1540 в .../install_ragent/defaults/main.yml, если нужно переопределить, то раскоментируйте строку и замените на требуемое значение
    SRV1CV8_REGPORT: 2541 # Порт запуска rmngr, Значение по умолчанию 1541 в .../install_ragent/defaults/main.yml, если нужно переопределить, то раскоментируйте строку и замените на требуемое значение
    SRV1CV8_RANGE: 2560:2591 # Диапазон портов рабочих процессов, Значение по умолчанию 1560:1591 в .../install_ragent/defaults/main.yml если нужно переопределить, то раскоментируйте строку и замените на требуемое значение
    RAS_PORT: 2545 # Порт сервера администрирования, Значение по умолчанию 1545 в .../install_ras/defaults/main.yml если не задан, то ставиться не будет
    #RAS_PORT:  # Если не нужно ставить сервер администирования, то нужно раскоменить эту строчку
    #####################################################################################################################################

  roles:
    - install_ragent # Установка службы сервера 1С по требуемому порту
    - install_ras # Установка службы удаленного администрирования 1С


##########################################################################################################################################################################################################
#УСТАНОВКА ВЕБ СЕРВЕРА
- name: installing web servers
  hosts: web_servers 

  vars:
    
    #inst_deb_dir: /ansible/distr/deb # Директория с инсталами deb пакетов на сервере, в которые есть еще один уровень каталогов - переменная deb_dir, которые относятся к определенным ролям и уже в этом каталоге расположены deb-файлы, которые должны быть установлены. Значение по умолчанию задается в .../install_deb_packages/defaults/main.yml
    deb_dir: apache # каталог в директории inst_deb_dir в которой лежат инсталлы deb пакетов
    #ins_dir_dest: /distr/platform # директория на хосте куда нужно копировать файл установки платформы. Значение по умолчанию задается в .../install_1C/defaults/main.yml
    #ins_dir_src: /ansible/distr/platform # директория откуда нужно копировать файл установки платформы.  Значение по умолчанию задается в .../install_1C/defaults/main.yml
    onec_version_name: 8.3.21.1393 # версия платформы 1С
    flag_Remove_old_1C_service: false # Флаг, что не нужно удалять старые службы 1С. По умолчанию true 
    enable_components: ws # Устанавливемые компоненты платформы 1C
    
  roles:
    - install_1C # Установка компонента ws платформы
    - install_deb_packages # Установка apache и требуемых пакетов
    - setup_apache # Первоначальная настройка apache: включение модулей для работы apache, копирование сертификатов, установка конфигурации
    - restart_apache # Рестарт службы apache
    - publishing # Публикация базы и сервисов
    - restart_apache # Рестарт службы apache


#Пример дополнительной публикации базы 1С на хосте
- name: publication of 1c databases
  hosts: web_servers_add 

  vars:
    onec_version_name: 8.3.21.1393 # версия платформы 1С
    
  roles:
    #- publishing # Публикация базы и сервисов
    #- restart_apache # Рестарт службы apache

