- name: pass
  hosts: all

  vars_prompt:
    - name: ansible_password
      prompt: Пароль для подключения
      private: yes

##########################################################################################################################################################################################################
#УСТАНОВКА СЕРВЕРА 1С ПРЕДПРИЯТИЯ
- name: installing server 1С
  hosts: serv1C

  vars:
    inst_deb_dir: /ansible/distr/deb # Директория с инсталами deb пакетов на сервере, в которые есть еще один уровень каталогов - переменная deb_dir, которые относятся к определенным ролям и уже в этом каталоге расположены deb-файлы, которые должны быть установлены. Значение по умолчанию задается в .../install_deb_packages/defaults/main.yml
    deb_dir: for_platform_1C # каталог в директории inst_deb_dir в которой лежат инсталлы deb пакетов    
    temp_dir_1c: /var/1C # Директория, которая примонтирована на отдельную партицию для размещения темпа 1С. В ней будут папки серверов 1С.  
    inst_dir_scripts: /ansible/distr/scripts/ # Директория с скриптами
    ins_dir_dest: /home/ivanov_ii/distr/platform # директория на хосте куда нужно копировать файл установки платформы. 
    ins_dir_src: /ansible/distr/platform # директория откуда нужно копировать файл установки платформы.
    onec_version_name: 8.3.22.1851 # версия платформы 1С
    inst_dir_fonts: ./fonts # Директория откуда нужно копировать шрифты. Они разложены по папкам и находятся в папке truetype
    
    #####################################################################################################################################
    # Переопределение запуска службы сервера, если не нужно, то закоменить, значения по умолчанию заданы в defaults file for install_1C
    #SRV1CV8_DEBUG: '"-debug -http"' # признак необходимости запуска сервера отладки под http. Значение по умолчанию пусто (отладка отключена) в .../install_ragent/defaults/main.yml Если нужно включить, то раскоментируйте строку
    #SRV1CV8_DEBUG: -debug # признак необходимости запуска сервера отладки под tcp. по умолчанию отладка отключена. Если нужно включить, то раскоментируйте строку
    #SRV1CV8_PORT: 1540 # Порт запуска ragent, Значение по умолчанию 1540 в .../install_ragent/defaults/main.yml, если нужно переопределить, то раскоментируйте строку и замените на требуемое значение
    #SRV1CV8_REGPORT: 1541 # Порт запуска rmngr, Значение по умолчанию 1541 в .../install_ragent/defaults/main.yml, если нужно переопределить, то раскоментируйте строку и замените на требуемое значение
    #SRV1CV8_RANGE: 1560:1591 # Диапазон портов рабочих процессов, Значение по умолчанию 1560:1591 в .../install_ragent/defaults/main.yml если нужно переопределить, то раскоментируйте строку и замените на требуемое значение
    #RAS_PORT: 1545 # Порт сервера администрирования, Значение по умолчанию 1545 в .../install_ras/defaults/main.yml если не задан, то ставиться не будет
    #RAS_PORT:  # Если не нужно ставить сервер администрирования, то нужно раскоменить эту строчку
    #####################################################################################################################################

  roles:
    - install_deb_packages # Установка пакета fontconfig
    - first_setup # Первоначальная установка - создание пользователя 1С, группы пользователей, каталогов программы, копирование шрифтов 
    - install_1C # Копирование файла установки 1С и запуск скрипта установки сервера 1С
    - install_ragent # Установка службы сервера 1С по требуемому порту
    - install_ras # Установка службы удаленного администрирования 1С

##########################################################################################################################################################################################################
#НАСТРОЙКА МОНИТОРИНГА 1С
- name: Monitoring 1С
  hosts: serv1C

  vars:
    script_path: /ansible/distr/scripts_monitoring/zabbix_exporter.py # Путь к скрипту мониторинга 1С
    repo_path: /ansible/distr/scripts_monitoring/zabbix-5.list # Путь к списку с репозиториями для установки zabbix-sender
    runmode: "all" # 1c - проверка доступности базы в кластере 1с, pg - проверка доступности базы в СУБД, lic - проверка доступности сервера лицензирования, all - проверка всех состояний
    base_name: "base_name" # Имя базы в 1С или СУБД
    pg_server: "pg_server" # Имя сервера Postgres
    pg_user: "pg_user" # Имя пользователя Postgres
    pg_pass: 'pg_pass' # Пароль пользователя Postgres, знаки процента (%) нужно экранировать обратной косой чертой т.е. "my%pas%s" будет "my\%pas\%s"
    ras_cluster_user: "ras_cluster_user" # Имя администратора кластера 1С
    ras_cluster_pass: 'ras_cluster_pass' # Пароль администратора кластера 1С

  roles:
    - monitoring_1C # Установка необходимых пакетов и добавление в CRON заданий, для выполнения скрипта, каждые 30 секунд
