- name: pass
  hosts: all

  vars_prompt:
    - name: ansible_password
      prompt: Пароль для подключения
      private: yes

##########################################################################################################################################################################################################
#УСТАНОВКА ВЕБ СЕРВЕРА
- name: installing web server
  hosts: serv1C

  vars:
    
    ins_dir_dest: /home/ivanov_ii/platform # директория на хосте куда нужно копировать файл установки платформы. Значение по умолчанию задается в .../install_1C/defaults/main.yml
    ins_dir_src: /ansible/distr/platform # директория откуда нужно копировать файл установки платформы.  Значение по умолчанию задается в .../install_1C/defaults/main.yml
    onec_version_name: 8.3.22.1851 # версия платформы 1С
    flag_Remove_old_1C_service: false # Флаг, что не нужно удалять старые службы 1С. По умолчанию true 
    enable_components: ws # Устанавливемые компоненты платформы 1C
    
  roles:
    - install_1C # Установка компонента ws платформы
    - setup_apache # Первоначальная установка и настройка apache: включение модулей, копирование сертификатов, установка конфигурации
    - restart_apache # Рестарт службы apache
    #- publishing # Публикация базы и сервисов
    #- restart_apache # Рестарт службы apache
